// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Heartbeat {
    pub last_recv_seq: u64,
}

impl BinaryCodec for Heartbeat {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u64(self.last_recv_seq);
    }

    fn decode(buf: &mut Bytes) -> Option<Heartbeat> {
        let last_recv_seq = buf.get_u64();
        Some(Self { last_recv_seq })
    }
}

#[cfg(test)]
mod heartbeat_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_heartbeat_codec() {
        let original = Heartbeat {
            last_recv_seq: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Heartbeat::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
