// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct InstrAck {
    pub instr_id: u64,
    pub result: u8,
    pub ts_ns: u64,
}

impl BinaryCodec for InstrAck {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u64(self.instr_id);
        buf.put_u8(self.result);
        buf.put_u64(self.ts_ns);
    }

    fn decode(buf: &mut Bytes) -> Option<InstrAck> {
        let instr_id = buf.get_u64();
        let result = buf.get_u8();
        let ts_ns = buf.get_u64();
        Some(Self {
            instr_id,
            result,
            ts_ns,
        })
    }
}

#[cfg(test)]
mod instr_ack_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_instr_ack_codec() {
        let original = InstrAck {
            instr_id: 123456789,
            result: 42,
            ts_ns: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = InstrAck::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
