// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Instruction {
    pub instr_id: u64,
    pub instr_type: u16,
    pub target_type: u8,
    pub target: String,
    pub expiry_ns: u64,
    pub operator: String,
    pub ts_ns: u64,
}

impl BinaryCodec for Instruction {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u64(self.instr_id);
        buf.put_u16(self.instr_type);
        buf.put_u8(self.target_type);
        put_char_array(buf, &self.target, 32);
        buf.put_u64(self.expiry_ns);
        put_char_array(buf, &self.operator, 16);
        buf.put_u64(self.ts_ns);
    }

    fn decode(buf: &mut Bytes) -> Option<Instruction> {
        let instr_id = buf.get_u64();
        let instr_type = buf.get_u16();
        let target_type = buf.get_u8();
        let target = get_char_array(buf, 32)?;
        let expiry_ns = buf.get_u64();
        let operator = get_char_array(buf, 16)?;
        let ts_ns = buf.get_u64();
        Some(Self {
            instr_id,
            instr_type,
            target_type,
            target,
            expiry_ns,
            operator,
            ts_ns,
        })
    }
}

#[cfg(test)]
mod instruction_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_instruction_codec() {
        let original = Instruction {
            instr_id: 123456789,
            instr_type: 1234,
            target_type: 42,
            target: vec!['a'; 32].into_iter().collect::<String>(),
            expiry_ns: 123456789,
            operator: vec!['a'; 16].into_iter().collect::<String>(),
            ts_ns: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Instruction::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
