// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct LogonAck {
    pub engine_id: String,
    pub session_id: u64,
    pub heartbeat_ms: u16,
    pub accept: u8,
    pub reason: String,
}

impl BinaryCodec for LogonAck {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.engine_id, 16);
        buf.put_u64(self.session_id);
        buf.put_u16(self.heartbeat_ms);
        buf.put_u8(self.accept);
        put_char_array(buf, &self.reason, 32);
    }

    fn decode(buf: &mut Bytes) -> Option<LogonAck> {
        let engine_id = get_char_array(buf, 16)?;
        let session_id = buf.get_u64();
        let heartbeat_ms = buf.get_u16();
        let accept = buf.get_u8();
        let reason = get_char_array(buf, 32)?;
        Some(Self {
            engine_id,
            session_id,
            heartbeat_ms,
            accept,
            reason,
        })
    }
}

#[cfg(test)]
mod logon_ack_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_logon_ack_codec() {
        let original = LogonAck {
            engine_id: vec!['a'; 16].into_iter().collect::<String>(),
            session_id: 123456789,
            heartbeat_ms: 1234,
            accept: 42,
            reason: vec!['a'; 32].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = LogonAck::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
