// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Logon {
    pub gateway_id: String,
    pub role: u8,
    pub proto_ver: u16,
    pub heartbeat_ms: u16,
    pub caps: u32,
}

impl BinaryCodec for Logon {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.gateway_id, 16);
        buf.put_u8(self.role);
        buf.put_u16(self.proto_ver);
        buf.put_u16(self.heartbeat_ms);
        buf.put_u32(self.caps);
    }

    fn decode(buf: &mut Bytes) -> Option<Logon> {
        let gateway_id = get_char_array(buf, 16)?;
        let role = buf.get_u8();
        let proto_ver = buf.get_u16();
        let heartbeat_ms = buf.get_u16();
        let caps = buf.get_u32();
        Some(Self {
            gateway_id,
            role,
            proto_ver,
            heartbeat_ms,
            caps,
        })
    }
}

#[cfg(test)]
mod logon_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_logon_codec() {
        let original = Logon {
            gateway_id: vec!['a'; 16].into_iter().collect::<String>(),
            role: 42,
            proto_ver: 1234,
            heartbeat_ms: 1234,
            caps: 123456,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Logon::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
