// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct NewOrderReq {
    pub req_id: u64,
    pub channel_id: u16,
    pub adapter: u8,
    pub account: String,
    pub account_group: String,
    pub cl_ord_id: String,
    pub security_id: String,
    pub market: u8,
    pub side: u8,
    pub price: i64,
    pub order_qty: i64,
    pub ord_type: u8,
    pub time_in_force: u8,
    pub pbu: String,
    pub transact_time: u64,
    pub ts_recv_ns: u64,
    pub raw_ref: u64,
}

impl BinaryCodec for NewOrderReq {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u64(self.req_id);
        buf.put_u16(self.channel_id);
        buf.put_u8(self.adapter);
        put_char_array(buf, &self.account, 16);
        put_char_array(buf, &self.account_group, 16);
        put_char_array(buf, &self.cl_ord_id, 16);
        put_char_array(buf, &self.security_id, 12);
        buf.put_u8(self.market);
        buf.put_u8(self.side);
        buf.put_i64(self.price);
        buf.put_i64(self.order_qty);
        buf.put_u8(self.ord_type);
        buf.put_u8(self.time_in_force);
        put_char_array(buf, &self.pbu, 8);
        buf.put_u64(self.transact_time);
        buf.put_u64(self.ts_recv_ns);
        buf.put_u64(self.raw_ref);
    }

    fn decode(buf: &mut Bytes) -> Option<NewOrderReq> {
        let req_id = buf.get_u64();
        let channel_id = buf.get_u16();
        let adapter = buf.get_u8();
        let account = get_char_array(buf, 16)?;
        let account_group = get_char_array(buf, 16)?;
        let cl_ord_id = get_char_array(buf, 16)?;
        let security_id = get_char_array(buf, 12)?;
        let market = buf.get_u8();
        let side = buf.get_u8();
        let price = buf.get_i64();
        let order_qty = buf.get_i64();
        let ord_type = buf.get_u8();
        let time_in_force = buf.get_u8();
        let pbu = get_char_array(buf, 8)?;
        let transact_time = buf.get_u64();
        let ts_recv_ns = buf.get_u64();
        let raw_ref = buf.get_u64();
        Some(Self {
            req_id,
            channel_id,
            adapter,
            account,
            account_group,
            cl_ord_id,
            security_id,
            market,
            side,
            price,
            order_qty,
            ord_type,
            time_in_force,
            pbu,
            transact_time,
            ts_recv_ns,
            raw_ref,
        })
    }
}

#[cfg(test)]
mod new_order_req_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_new_order_req_codec() {
        let original = NewOrderReq {
            req_id: 123456789,
            channel_id: 1234,
            adapter: 42,
            account: vec!['a'; 16].into_iter().collect::<String>(),
            account_group: vec!['a'; 16].into_iter().collect::<String>(),
            cl_ord_id: vec!['a'; 16].into_iter().collect::<String>(),
            security_id: vec!['a'; 12].into_iter().collect::<String>(),
            market: 42,
            side: 42,
            price: -123456789,
            order_qty: -123456789,
            ord_type: 42,
            time_in_force: 42,
            pbu: vec!['a'; 8].into_iter().collect::<String>(),
            transact_time: 123456789,
            ts_recv_ns: 123456789,
            raw_ref: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = NewOrderReq::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
