// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use byteorder::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::cancel_reject::*;
use crate::cancel_req::*;
use crate::instr_ack::*;
use crate::instruction::*;
use crate::new_order_req::*;
use crate::order_confirm::*;
use crate::order_reject::*;
use crate::risk_result::*;
use crate::trade_report::*;

#[derive(Debug, Clone, PartialEq)]
pub enum RbpBinaryBodyEnum {
    NewOrderReq(NewOrderReq),
    CancelReq(CancelReq),
    OrderConfirm(OrderConfirm),
    TradeReport(TradeReport),
    CancelReject(CancelReject),
    OrderReject(OrderReject),
    RiskResult(RiskResult),
    Instruction(Instruction),
    InstrAck(InstrAck),
}

#[derive(Debug, Clone, PartialEq)]
pub struct RbpBinary {
    pub msg_type: u32,
    pub version: u16,
    pub flags: u16,
    pub msg_seq: u64,
    pub ts_ns: u64,
    pub body_len: u32,
    pub checksum: u32,
    pub body: RbpBinaryBodyEnum,
}

impl BinaryCodec for RbpBinary {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32(self.msg_type);
        buf.put_u16(self.version);
        buf.put_u16(self.flags);
        buf.put_u64(self.msg_seq);
        buf.put_u64(self.ts_ns);
        let body_len_pos = buf.len();
        buf.put_u32(0);

        buf.put_u32(self.checksum);
        let body_start = buf.len();
        match &self.body {
            RbpBinaryBodyEnum::NewOrderReq(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::CancelReq(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::OrderConfirm(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::TradeReport(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::CancelReject(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::OrderReject(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::RiskResult(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::Instruction(msg) => msg.encode(buf),
            RbpBinaryBodyEnum::InstrAck(msg) => msg.encode(buf),
        }
        let body_end = buf.len();
        BigEndian::write_u32(
            &mut buf[body_len_pos..body_len_pos + 4],
            (body_end - body_start) as u32,
        );
    }

    fn decode(buf: &mut Bytes) -> Option<RbpBinary> {
        let msg_type = buf.get_u32();
        let version = buf.get_u16();
        let flags = buf.get_u16();
        let msg_seq = buf.get_u64();
        let ts_ns = buf.get_u64();
        let body_len = buf.get_u32();
        let checksum = buf.get_u32();
        let body = match msg_type {
            16 => RbpBinaryBodyEnum::NewOrderReq(NewOrderReq::decode(buf)?),
            17 => RbpBinaryBodyEnum::CancelReq(CancelReq::decode(buf)?),
            18 => RbpBinaryBodyEnum::OrderConfirm(OrderConfirm::decode(buf)?),
            19 => RbpBinaryBodyEnum::TradeReport(TradeReport::decode(buf)?),
            20 => RbpBinaryBodyEnum::CancelReject(CancelReject::decode(buf)?),
            21 => RbpBinaryBodyEnum::OrderReject(OrderReject::decode(buf)?),
            32 => RbpBinaryBodyEnum::RiskResult(RiskResult::decode(buf)?),
            48 => RbpBinaryBodyEnum::Instruction(Instruction::decode(buf)?),
            49 => RbpBinaryBodyEnum::InstrAck(InstrAck::decode(buf)?),
            _ => return None,
        };
        Some(Self {
            msg_type,
            version,
            flags,
            msg_seq,
            ts_ns,
            body_len,
            checksum,
            body,
        })
    }
}

#[cfg(test)]
mod rbp_binary_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_rbp_binary_codec() {
        let mut original = RbpBinary {
            version: 1234,
            flags: 1234,
            msg_seq: 123456789,
            ts_ns: 123456789,
            body_len: 0,
            checksum: 123456,
            msg_type: 16,
            body: RbpBinaryBodyEnum::NewOrderReq(NewOrderReq {
                req_id: 123456789,
                channel_id: 1234,
                adapter: 42,
                account: vec!['a'; 16].into_iter().collect::<String>(),
                account_group: vec!['a'; 16].into_iter().collect::<String>(),
                cl_ord_id: vec!['a'; 16].into_iter().collect::<String>(),
                security_id: vec!['a'; 12].into_iter().collect::<String>(),
                market: 42,
                side: 42,
                price: -123456789,
                order_qty: -123456789,
                ord_type: 42,
                time_in_force: 42,
                pbu: vec!['a'; 8].into_iter().collect::<String>(),
                transact_time: 123456789,
                ts_recv_ns: 123456789,
                raw_ref: 123456789,
            }),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = RbpBinary::decode(&mut bytes).unwrap();
        original.body_len = decoded.body_len;
        assert_eq!(original, decoded);
    }
}
