// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct SessionReject {
    pub err_code: u16,
    pub text: String,
}

impl BinaryCodec for SessionReject {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u16(self.err_code);
        put_char_array(buf, &self.text, 48);
    }

    fn decode(buf: &mut Bytes) -> Option<SessionReject> {
        let err_code = buf.get_u16();
        let text = get_char_array(buf, 48)?;
        Some(Self { err_code, text })
    }
}

#[cfg(test)]
mod session_reject_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_session_reject_codec() {
        let original = SessionReject {
            err_code: 1234,
            text: vec!['a'; 48].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = SessionReject::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
