// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct TradeReport {
    pub req_id: u64,
    pub channel_id: u16,
    pub adapter: u8,
    pub account: String,
    pub cl_ord_id: String,
    pub order_id: String,
    pub exec_id: String,
    pub exec_type: u8,
    pub ord_status: u8,
    pub security_id: String,
    pub side: u8,
    pub last_px: i64,
    pub last_qty: i64,
    pub cum_qty: i64,
    pub leaves_qty: i64,
    pub ts_ns: u64,
    pub raw_ref: u64,
}

impl BinaryCodec for TradeReport {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u64(self.req_id);
        buf.put_u16(self.channel_id);
        buf.put_u8(self.adapter);
        put_char_array(buf, &self.account, 16);
        put_char_array(buf, &self.cl_ord_id, 16);
        put_char_array(buf, &self.order_id, 16);
        put_char_array(buf, &self.exec_id, 16);
        buf.put_u8(self.exec_type);
        buf.put_u8(self.ord_status);
        put_char_array(buf, &self.security_id, 12);
        buf.put_u8(self.side);
        buf.put_i64(self.last_px);
        buf.put_i64(self.last_qty);
        buf.put_i64(self.cum_qty);
        buf.put_i64(self.leaves_qty);
        buf.put_u64(self.ts_ns);
        buf.put_u64(self.raw_ref);
    }

    fn decode(buf: &mut Bytes) -> Option<TradeReport> {
        let req_id = buf.get_u64();
        let channel_id = buf.get_u16();
        let adapter = buf.get_u8();
        let account = get_char_array(buf, 16)?;
        let cl_ord_id = get_char_array(buf, 16)?;
        let order_id = get_char_array(buf, 16)?;
        let exec_id = get_char_array(buf, 16)?;
        let exec_type = buf.get_u8();
        let ord_status = buf.get_u8();
        let security_id = get_char_array(buf, 12)?;
        let side = buf.get_u8();
        let last_px = buf.get_i64();
        let last_qty = buf.get_i64();
        let cum_qty = buf.get_i64();
        let leaves_qty = buf.get_i64();
        let ts_ns = buf.get_u64();
        let raw_ref = buf.get_u64();
        Some(Self {
            req_id,
            channel_id,
            adapter,
            account,
            cl_ord_id,
            order_id,
            exec_id,
            exec_type,
            ord_status,
            security_id,
            side,
            last_px,
            last_qty,
            cum_qty,
            leaves_qty,
            ts_ns,
            raw_ref,
        })
    }
}

#[cfg(test)]
mod trade_report_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_trade_report_codec() {
        let original = TradeReport {
            req_id: 123456789,
            channel_id: 1234,
            adapter: 42,
            account: vec!['a'; 16].into_iter().collect::<String>(),
            cl_ord_id: vec!['a'; 16].into_iter().collect::<String>(),
            order_id: vec!['a'; 16].into_iter().collect::<String>(),
            exec_id: vec!['a'; 16].into_iter().collect::<String>(),
            exec_type: 42,
            ord_status: 42,
            security_id: vec!['a'; 12].into_iter().collect::<String>(),
            side: 42,
            last_px: -123456789,
            last_qty: -123456789,
            cum_qty: -123456789,
            leaves_qty: -123456789,
            ts_ns: 123456789,
            raw_ref: 123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = TradeReport::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
